import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";
import { getCorsHeaders } from "../_shared/cors.ts";
serve(async (req) => {
  // Get CORS headers based on origin
  const origin = req.headers.get('origin');
  const corsHeaders = getCorsHeaders(origin);

  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { client_id, client_name, goals, lifestyle, age, dietType } = await req.json();
    console.log('Generating action plan for client:', client_id);

    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Create detailed visual design prompt
    const imagePrompt = `Create a clean, professional wellness action plan infographic for ${client_name}, a ${age}-year-old following a ${dietType === 'veg' ? 'vegetarian' : dietType === 'non_veg' ? 'non-vegetarian' : 'vegan'} diet.

Design specifications:
- Title at top: "Your Personalized Action Plan - ${client_name}"
- Color scheme: Wellness green (#2E8B57) as primary, white background, soft accents
- Modern, minimalist, motivational style with clean typography

Layout sections (arrange vertically):

1. GOALS SECTION (top):
   - Icon: Target/bullseye
   - Text: "${goals}"
   - Style: Bold, inspiring

2. DAILY TIMELINE (middle-left):
   - Visual timeline from 6 AM to 10 PM
   - Activity blocks with icons:
     * 6-7 AM: Wake up, water (droplet icon)
     * 8 AM: Breakfast (utensils icon)
     * 12-1 PM: Lunch (utensils icon)
     * 5 PM: Evening snack (apple icon)
     * 6 PM: Exercise (running figure)
     * 8 PM: Dinner (utensils icon)
     * 10 PM: Sleep (moon icon)

3. HABIT TRACKER GRID (middle-right):
   - 7-day grid (Mon-Sun)
   - Rows: Water (8 cups), Meals (4), Exercise (30min), Sleep (7-8h)
   - Checkbox style squares

4. DO'S SECTION (bottom-left, green background):
   - Green checkmarks
   - 5 items based on ${lifestyle} lifestyle and ${dietType} diet:
     * Drink 2L water daily
     * Eat balanced meals
     * Exercise regularly
     * Get adequate sleep
     * Track progress

5. DON'TS SECTION (bottom-right, red/orange accent):
   - Red X marks
   - 5 items:
     * Skip meals
     * Overeat processed foods
     * Neglect hydration
     * Stay sedentary
     * Ignore hunger cues

Style: Professional infographic, suitable for printing, high contrast, clear hierarchy, motivational tone. Ultra high resolution 16:9 aspect ratio.`;

    console.log('Calling OpenAI DALL-E for image generation...');

    // Call OpenAI DALL-E for image generation
    const aiResponse = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${Deno.env.get('OPENAI_API_KEY')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'dall-e-3',
        prompt: imagePrompt,
        n: 1,
        size: '1792x1024',
        quality: 'standard'
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI image generation failed:', aiResponse.status, errorText);
      throw new Error(`AI image generation failed: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    const imageUrl = aiData.data?.[0]?.url;

    if (!imageUrl) {
      throw new Error('No image generated by AI');
    }

    console.log('Action plan image generated successfully');

    // Fetch the image from the URL
    const imageResponse = await fetch(imageUrl);
    const imageBuffer = new Uint8Array(await imageResponse.arrayBuffer());

    // Upload to storage
    const fileName = `${client_id}/action-plan-${Date.now()}.png`;
    const { data: uploadData, error: uploadError } = await supabaseClient
      .storage
      .from('action-plan-images')
      .upload(fileName, imageBuffer, {
        contentType: 'image/png',
        upsert: false,
      });

    if (uploadError) {
      console.error('Error uploading image:', uploadError);
      throw uploadError;
    }

    console.log('Image uploaded to storage:', fileName);

    // Get public URL
    const { data: { publicUrl } } = supabaseClient
      .storage
      .from('action-plan-images')
      .getPublicUrl(fileName);

    // Structure habits, dos, and donts
    const dailyHabits = {
      morning: 'Wake up at consistent time, drink water',
      meals: 'Balanced breakfast, lunch, evening snack, dinner',
      exercise: '30 minutes activity',
      evening: 'Light dinner, no late-night eating',
      sleep: '7-8 hours quality sleep',
    };

    const dos = [
      'Drink 2 liters of water daily',
      'Eat balanced meals at regular times',
      'Exercise for at least 30 minutes',
      'Get adequate sleep (7-8 hours)',
      'Track your progress consistently',
    ];

    const donts = [
      'Skip meals or irregular eating',
      'Overeat processed or junk foods',
      'Neglect hydration throughout day',
      'Remain sedentary for long periods',
      'Ignore hunger or fullness cues',
    ];

    // Insert action plan into database
    const { data: actionPlan, error: insertError } = await supabaseClient
      .from('action_plans')
      .insert({
        client_id,
        plan_image_url: publicUrl,
        goals,
        lifestyle,
        age: parseInt(age),
        diet_type: dietType,
        daily_habits: dailyHabits,
        dos,
        donts,
      })
      .select()
      .single();

    if (insertError) {
      console.error('Error inserting action plan:', insertError);
      throw insertError;
    }

    console.log('Action plan saved to database:', actionPlan.id);

    return new Response(
      JSON.stringify({
        plan_id: actionPlan.id,
        image_url: publicUrl,
        habits: dailyHabits,
        dos,
        donts,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error: any) {
    console.error('Error in generate-action-plan:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: error.message.includes('429') ? 429 : error.message.includes('402') ? 402 : 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});
